# Generated by Django 5.2.6 on 2025-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
