# Generated by Django 5.2.8 on 2025-11-29 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_date_app_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
